# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba0aad2b23b0b91bf0304ca9523b12f8580f7ac956fb7ab9dbe5f74082274be4aab0e4d3921e83fea15d3669a460f5a0c2d6ec8fde8f5d1d7746ff70f2efbf91

test:
  secret_key_base: 312e864fdcb852a8a526551e51dd457e97e60cb4fe02fbfb7f394a57964b714d043a477f0710271f5739313d1b1f2f2b955dc9e4f6b7a8115aa77b76b2342fec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
